<a href="https://colab.research.google.com/github/PiyushPanwarFST/practice/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd # Importing the pandas library and aliasing it as 'pd'
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"

# Column names based on the dataset description
column_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']

# Read the dataset from the URL
# Note: The dataset uses various delimiters and contains missing values denoted as '?'
df = pd.read_csv(url, delim_whitespace=True, names=column_names, na_values='?', comment='\t')

# Display the first few rows of the dataframe
df.head()

<ipython-input-3-28c953693156>:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(url, delim_whitespace=True, names=column_names, na_values='?', comment='\t')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [14]:
# prompt: check that any column have missing or not if yes then handle them

import pandas as pd # Importing the pandas library and aliasing it as 'pd'
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"

# Column names based on the dataset description
column_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']

# Read the dataset from the URL
# Note: The dataset uses various delimiters and contains missing values denoted as '?'
df = pd.read_csv(url, delim_whitespace=True, names=column_names, na_values='?', comment='\t')

# Check for missing values in each column
print(df.isnull().sum())

<ipython-input-14-969691be6109>:11: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(url, delim_whitespace=True, names=column_names, na_values='?', comment='\t')

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [35]:
# Handle missing values (example: fill with the mean for numerical columns)
for col in ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

# Alternatively, you can drop rows with missing values
# df.dropna(inplace=True)

# Verify that there are no more missing values (optional)
print(df.isnull().sum())

# Assuming 'mpg' is your target variable and the rest are features
X = df.drop('mpg', axis=1)
y = df['mpg']

print(X.shape)

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64
(398, 8)

In [36]:
# prompt: just wrote the template for train_test_split by 80% & 20%

import pandas as pd
from sklearn.model_selection import train_test_split

# ... (Your existing code to load and preprocess the data) ...



# # Convert categorical features to numerical ones using one-hot encoding if needed
# X = pd.get_dummies(X, columns=['origin', 'car_name'], drop_first=True)

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Now you can use X_train, X_test, y_train, and y_test for model training and evaluation
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (318, 8)
X_test shape: (80, 8)
y_train shape: (318,)
y_test shape: (80,)

In [32]:
# prompt: now start doing model training by linear regression, use r2score , model.score use mean squared error as well

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# ... (Your existing code to load and preprocess the data) ...

# Assuming 'mpg' is your target variable and the rest are features
X = df.drop('mpg', axis=1)
y = df['mpg']

# Convert categorical features to numerical using one-hot encoding if needed
X = df.drop(columns=['origin', 'car_name']) # Pass columns to be dropped as a list

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
model_score = model.score(X_test, y_test)


print(f"R-squared: {r2}")
print(f"Mean Squared Error: {mse}")
print(f"Model Score: {model_score}")

R-squared: 1.0
Mean Squared Error: 6.535712599756082e-29
Model Score: 1.0

In [27]:
y_pred[:5]  # Display the first 5 elements of the NumPy array

array([33., 28., 19., 13., 14.])

In [26]:
y_test.head()

198    33.0
396    28.0
33     19.0
208    13.0
93     14.0
Name: mpg, dtype: float64